version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: super-secret-key-for-local-dev-only
      DEBUG: "True"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"