services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: securepass123
      POSTGRES_DB: django_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d django_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: super-secret-key-for-local-dev-only
      DEBUG: "True"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      DB_HOST: db
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: securepass123
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data_new: