# Generated by Django 6.0.4 on 2026-08-14 12:35

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=projects.models.get_expiration_date),
        ),
    ]
