# Generated by Django 6.0.4 on 2026-07-11 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 18, 12, 32, 42, 307012, tzinfo=datetime.timezone.utc)),
        ),
    ]
