# Generated by Django 6.0.4 on 2026-08-06 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 13, 21, 37, 40, 537671, tzinfo=datetime.timezone.utc)),
        ),
    ]
