# Generated by Django 6.0.4 on 2026-08-07 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 14, 2, 13, 59, 348144, tzinfo=datetime.timezone.utc)),
        ),
    ]
