# Generated by Django 6.0.4 on 2026-08-14 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_invitation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 21, 12, 10, 26, 260589, tzinfo=datetime.timezone.utc)),
        ),
    ]
