echo 'name: Just Test If Docker Builds

on:
  pull_request:
    branches: [ main ]

jobs:
  test-docker:
    name: Try to build the compose file
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Build everything in docker-compose.yml
        run: docker-compose build' > .github/workflows/test-build.yml